### ISSUE TITLE
Not working on Home V.3 - Firmware-Version: HOME 4.6

### ISSUE THREAD

**Issue by swissglider** [dan1-de/ioBroker.anelhut#14]
**Describe the bug**  
I have installed the anelhut adapter on my iobroker.
I have done the standard configuration as also configured on my Anel Net Power Control Home.
I can connect over the web interface without any problems.

But on iobroker I can not connect and get the following errors in the log:
```
Adapter anelhut starting..
Found: 1 devices in configuration
Found device in config: test | 192.168.....
Adapter anelhut initialized
**UDP Server Error: Error: bind EACCES 0.0.0.0:77
at dgram.js:338:20
at processTicksAndRejections (internal/process/task_queues.js:85:21)**
check user admin pw iobroker: true
check group user admin group admin: false
```

the user I configured is admin and has all the rights

Is the adapter really working on HOME ?

**Comment by dan1-de** [comment]
Hi @swissglider, 
sorry for the late answer, but i have not seen the notification until today.

The problem is in this line:  
"**UDP Server Error: Error: bind EACCES 0.0.0.0:77"**

**Explanation and Solution:**
The UDP Server can not bind to the port 77. This error occurs mostly, if the user is no root, because for listening on ports lower than 1024 the user needs root permissions. Can you change the port to a port higher than 1024 (eg. 2077) and try again ? 
You have to do the following steps:
1. Goto Webinterface of your ANEL Device and change the Send Port to 2077. 
![image](https://user-images.githubusercontent.com/52854781/118610050-aaf6cb00-b7bb-11eb-8ba9-366c456c3f75.png)
2. Configure IOBroker Adapter and change the UDPRecievePort to 2077. 
![image](https://user-images.githubusercontent.com/52854781/118610223-d4175b80-b7bb-11eb-8419-c812655c0a4c.png)

3. Reboot ANEL Device and Restart IOBroker Adapter




Please let me know, if it works now.

**Comment by dan1-de** [comment]
I will close this issue now due to no response.
